### ISSUE TITLE
提示我json解析失败,不可以识别 token '<' 

### ISSUE THREAD

**Issue by shanbozhu** [hugohua/react-native-demo#2]
您好,  我下载运行了您的demo, 提示我json解析失败,不可以识别 token '<' ,界面也能出来,但是不全,不知道哪里错了, 初次运行react, 还请多多指教.

**Comment by dellheng** [comment]
1. json解析错误和tab 不能显示原因是
   react-native-demo/component/Tabs.js
   使用了天猫的这个地址无法访问了 http://www.tmall.com/go/rgn/3c/wh-fp-m-index-teh.php?1
   原来能访问的时候是返回json, 现在返回的是 “很抱歉，您查看的页面找不到了”的HTML，所以报错“json解析失败,不可以识别 token '<'” ，作者应该是逆向工程获得的地址，现在tmall改版了，不知道这个地址现在是什么了
2. 列表图片不显示原因是
   Unrecognized tag protocol: //img.alicdn.com/bao/uploaded/TB1eIViMXXXXXa2apXXSutbFXXX.jpg 

```
react-native-demo/component/ItemCell.js
将<Image style={styles.goodImg} source={{uri : item.img}} />
修改为
<Image style={styles.goodImg} source={{uri : 'http:' + item.img}} />
就可以显示了
```

**Comment by shanbozhu** [comment]
谢谢解答

**Comment by hugohua** [comment]
master分支已经修复 api接口下线的问题。
mock数据也放到了根目录下了，感谢支持
